# Generated by Django 6.0.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('synopsis', models.TextField()),
                ('kind', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=10)),
                ('release_year', models.PositiveIntegerField()),
                ('runtime_minutes', models.PositiveIntegerField(help_text='Runtime in minutes')),
                ('content_rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('TV-MA', 'TV-MA')], default='PG-13', max_length=6)),
                ('imdb_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='backdrops/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the homepage hero')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_new_release', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='titles', to='catalog.genre')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
