# Generated by Django 6.0.6 on 2026-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
