# Generated by Django 6.0.6 on 2026-07-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_movie_video_key'),
    ]

    operations = [
    ]
